# Site
title:              Even More Your Own
bio:                'Even More Your Own is Jon Ford, a musician and producer from Bloomington Indiana.'
description:        "Even More Your Own is Jon Ford, a musician and producer from Bloomington Indiana."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/waves-small.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-39450962-3
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
spotify:            1KnrzPttA3H2kLkcO8ZMqw
apple-music:        broken-threads/id1289902309
email:              evenmoreyourown@gmail.com
#twitter:           username
facebook:           evenmoreyourown
#github-url:        username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
instagram:          evenmoreyourown
#lastfm:            jondavidford
#foursquare:        username
#youtube:           username
youtube-channel:    UC4GL60rP1V3pw4LAG0PliMA
#soundcloud:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
